### ISSUE TITLE
[FEATURE] Add crunchyroll free account support

### ISSUE THREAD

**Issue by jorensanbar** [OpenSTDL/CrunchyDL#10]
Some video dont require a subscription, like One Piece.

**Screenshots**
![imagen](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/25260359/f2bd536f-84d9-4d49-a9ad-c38ffdec8467)

**Comment by stratuma** [comment]
Since the new session limit this tool needs premium, otherwise the download would crash every two episodes.

**Comment by jorensanbar** [comment]
What a shame, because there are users who only download one video during the week.

**Comment by stratuma** [comment]
No offense, but you can get premium accounts for 30 cents a month, thats nothing considering you can download everything.

**Comment by TaMaGo-TTV** [comment]
> No offense, but you can get premium accounts for 30 cents a month, thats nothing considering you can download everything.

bro wo (schick mal link auf discord) XD

**Comment by stratuma** [comment]
> bro wo (schick mal link auf discord) XD

Einfach argentinische vpn holen und mit kreditkarte bezahlen
![IMG_0254](https://github.com/OpenSTDL/CrunchyDL/assets/166541445/2a8e67c6-4b64-422f-9367-5532d8944d05)

**Comment by TaMaGo-TTV** [comment]
yoooooo was, okay gut zu wissen XD 
dachte das geht nicht bei crunchy, aber geil dannmach ich nh neuen acc und abfahrt. 

Hab keine kreditkarte aber revolut sollte gehen oder?

**Comment by stratuma** [comment]
Wenn revolut Währungen tauschen kann dann ja

**Comment by TaMaGo-TTV** [comment]
> Wenn revolut Währungen tauschen kann dann ja

Ja das geht dort. Danke für die info

**Comment by TaMaGo-TTV** [comment]
Muss ich die vpn dann aktiv anlassen oder juckt das nicht so wie bei YouTube

**Comment by stratuma** [comment]
Ne vpn brauchst du nur fürs abonnieren, danach kannste crunchy auch ohne vpn nutzen

**Comment by jorensanbar** [comment]
Fixed, only replace the throw exception in get me data endpoint, to "return 1"

50 files downloaded without error or crashed and Free Account.

![imagen](https://github.com/OpenSTDL/CrunchyDL/assets/25260359/1e5de9e8-ee36-4056-b41b-009a193b186a)

**Comment by jorensanbar** [comment]
BTW, to avoid crashes, the episode endpont includes the IsPremiumRequired (BOOL) flag, with this the application can attempt to download or not when Account Details is null.

**Comment by stratuma** [comment]
Yeah I want to do that, I think its just useless to add free tier support, like come on, 30 cents.
But I will do it.

**Comment by jorensanbar** [comment]
I tried, but crunchy has already updated the Argentine prices, the cheapest is at 3299 ARG, which would be $4 USD per month :( 

But with the replacement of that line, any user can download the chapters available for the Free Tier

**Comment by stratuma** [comment]
Moving all feature requests to #14
