### ISSUE TITLE
[FEATURES] Implementation of new options

### ISSUE THREAD

**Issue by Vorffeed** [OpenSTDL/CrunchyDL#19]
Good ^_^
You could add new features that would be appreciated as:

1º Drop down menu with the right button to copy paste and not to go with ctr+v to paste the links.

2º Add to the configuration menu the default resolution, container and if you want the subtitles to be pasted or not, the container and the resolution, it would be better there than where they are right now, and not having to configure them every time you start the program.

3º Put in the download menu of the episode a menu where to choose if you want to download only subtitle, video, subtitle + video and subtitle + video without remuxing the subs inside the container, this option is good for the first two options, because many times the subs do not come well first that can be from another series or have uploaded it wrong only having three lines of subs and then crunchi corrects them, in my case I usually download video and subs separately because so I can check if the subs are well and only download the sub without having to download the video again.

4º Detect the correct type of link, that is, if I enter the link for episode 6 of season 2 to download that episode, that specific episode should appear for download and not the menu with season 1 to select all seasons and have to search and choose the episode you want to download again, if you enter the link of the series in general then it is fine for it to appear like that, but not the other way around.

5º check that if there is already a chapter with the same name in the destination folder that does not download and warn and then decide whether to download or not, because directly what it does is to crush it for the new one.

**Comment by stratuma** [comment]
I added 1º, on 2º I added quality, audio quality and output format configuration (I will add the other stuff later), I will add 3º 4º 5º  later.

**Comment by LordKimbou** [comment]
Since I have seen this post to implement options, and for not opening more posts...

Could you put one in "naming", to create a main directory with the name of the series only, and inside of this the directories the seasons directories would be created. I think that this way, everything would be more organized.
Thanks!! :)

**Comment by stratuma** [comment]
Good idea, I will look into it and release it with the new version.

**Comment by chazwarp923** [comment]
> Since I have seen this post to implement options, and for not opening more posts...
> 
> Could you put one in "naming", to create a main directory with the name of the series only, and inside of this the directories the seasons directories would be created. I think that this way, everything would be more organized. Thanks!! :)

This is already accomplish-able by just putting a / in the name you want it to use for the Season folder eg. "{seriesName}/Season {seasonNumberDD}"

**Comment by chazwarp923** [comment]
> Since I have seen this post to implement options, and for not opening more posts...
> 
> Could you put one in "naming", to create a main directory with the name of the series only, and inside of this the directories the seasons directories would be created. I think that this way, everything would be more organized. Thanks!! :)

This can already be done by simply putting a / in the season name eg. "{seriesName}/Season {seasonNumberDD}"

**Comment by chazwarp923** [comment]
Would it be possible to add the ability to download a whole playlist without having to add it episode by episode?
And the ability to record which episodes have been downloaded to an archive file similar to yt-dl?
Apologies if I'm asking for a lot. Keep up the great work!

**Comment by stratuma** [comment]
Moving all feature requests to #14
