### ISSUE TITLE
[FEATURES] Import L3 Widevine keys instead of pointing to it

### ISSUE THREAD

**Issue by deso85** [OpenSTDL/CrunchyDL#21]
I added a subfolder for the Widevine keys inside program file structure and after I updated the app the keys have been deleted. If it would be possible to import instead of pointing to them an update would (hopefully) not delete but keep them.

Thanks for concidering.

**Comment by stratuma** [comment]
I don't know, because rewriting the key input just for such a little gain seems useless for me.
Why don't you just make a folder with the keys outside of the application?

**Comment by deso85** [comment]
Would feel more convenient as I use the keys only for this purpose. Other technologies also import keys/certificates directly. I now have a folder beside the app folder but I see me in a few weeks wondering what these keys are ;-)

**Comment by stratuma** [comment]
I will add this after I finished the stuff i'm working on rn

**Comment by stratuma** [comment]
Moving all feature requests to #14
