### ISSUE TITLE
[BUG] "Download Update" button can't be clicked if files have already been downloaded

### ISSUE THREAD

**Issue by deso85** [OpenSTDL/CrunchyDL#34]
![image](https://github.com/OpenSTDL/CrunchyDL/assets/18106134/2d9be7a1-de49-4878-89c2-4dfe4ab67a3a)

It's not possible to click on the "Download Update" button when a new release is out and files have already been downloaded.

You could put the button in front of downloads or check for releases only when the programm started.

Please also consider a link to the release notes above the download button.

**Comment by stratuma** [comment]
Looks like I forgot to add z-index to the module.

**Comment by stratuma** [comment]
Fixed in v1.2.4
