### ISSUE TITLE
[FEATURES] [Cosmetics] Vorschlag für neue Features

### ISSUE THREAD

**Issue by LorenorZorro3000** [OpenSTDL/CrunchyDL#36]
1.  Mir ist eventuell ein Fehler bei der **Default Audio Quality** aufgefallen.
![Screenshot 2024-06-24 110056](https://github.com/OpenSTDL/CrunchyDL/assets/123302757/f3ff9280-89bd-4cff-901b-61a6a85c392e)
Müsste es nicht 32 kHz heißen in der Mitte und nicht das 2. Mal 44.10 kHz.

2. Als ich gerade ein Update über dein Programm gemacht habe (Interne Funktion), hat er nach den Neustarts des Programms alle Einstellungen verloren (Episode File Naming, alle Pfade, Widevine). Aber den Crunchyroll-Login hat er noch beibehalten.

3. Ein Button zum Entfernen der erfolgreich gedownloadeten Folgen wäre noch schön. Also das Entfernen der fertigen Folgen von der Downloadwarteschlange für eine bessere Übersicht.

4. Die Versionsnummer vom Programm auch in der Titelleiste anzeigen. Kein Muss, aber wäre schön gleich zu sehen, welche Version man hat.

5. Die Möglichkeit einer portablen Version für Windows wäre noch echt cool. Da ich gerne selber entscheiden möchte, in welchen Pfad ich das Programm haben will.

Vielen Dank schon mal.
MFG LorenorZorro

**Comment by stratuma** [comment]
Danke für die Vorschläge und Bugreports.
Ich werde mir die Punkte anschauen und eventuell integrieren

**Comment by stratuma** [comment]
Bezüglich der Audio Bitrate bin ich mir sicher, dass beide Spuren identisch sind:
![grafik](https://github.com/OpenSTDL/CrunchyDL/assets/166541445/92b2e59c-729f-411a-b683-842c0c79c00d)

Warum Crunchyroll zwei verschiedene Playlists mit gleicher Bitrate mitgibt ist mir noch unklar.

**Comment by LorenorZorro3000** [comment]
Ja cool, vielen Dank, dass du dich der Sache annimmst.

Mann merkt, dass du mit Herzblut hinter deinem Projekt stehst.
Respekt von mir dafür und dass du es auch bisher alleine stemmst.

Also von mir ein fettes Danke für deine tolle Arbeit❗👍🏻

**Comment by progithub2** [comment]
Kleiner Vorschalg von mir - wäre es auch möglich, dass man bei Sprache DE auch nur die Episoden angezeigt bekommt, die Dub DE sind? Also wenn jetzt von 1 bis 12 nur 8 DE sind und der rest noch JP.... bei CR3 war das ja gegen Ende auch so.... Wäre das möglich?

Zudem noch vielleicht die Möglichkeit den Download von einer bestimmten Episode zu pausieren/fortzusetzen (II)  oder mit X ganz zu unterbinden, ggf dann doch zu starten (>) oder per Mülleimer zu löschen....

**Comment by stratuma** [comment]
> Kleiner Vorschalg von mir - wäre es auch möglich, dass man bei Sprache DE auch nur die Episoden angezeigt bekommt, die Dub DE sind? Also wenn jetzt von 1 bis 12 nur 8 DE sind und der rest noch JP.... bei CR3 war das ja gegen Ende auch so.... Wäre das möglich?

Es wäre möglich aber es würde viel länger dauern um zu laden, da ich für jede folge die playlist fetchen müsste, bei hama's downloader ging das da er kein multi dub supported hat und deshalb einfach die verschiedenen dubs und die folgen angezeigt hat.

Download management ist schon auf der dev roadmap, hab aber momentan wenig zeit mich um den downloader zu kümmern

**Comment by stratuma** [comment]
Moving all feature requests to #14
