### ISSUE TITLE
[FEATURE] Download subtitles separate from the video (ASS/SRT)

### ISSUE THREAD

**Issue by dreezy-official** [OpenSTDL/CrunchyDL#39]
**If it were possible, you could add an option that allows you to download the subtitles separately from the video, for example in ASS or SRT format...**

**and you could create an option to delete completed downloads from the download playlist, if we select the button on the right side of the mouse or to stop the download.**
![2024-06-24_21-03-38](https://github.com/OpenSTDL/CrunchyDL/assets/75680397/5d90aff3-0515-4438-8f51-f525f4ccbf76)

**Comment by stratuma** [comment]
Separate download and download management is already in the dev roadmap #14 , I'm still working solo on this project so you need to wait until I find time to add this.

**Comment by stratuma** [comment]
Already in roadmap
