### ISSUE TITLE
[GUIDE] Error merging videos and audios

### ISSUE THREAD

**Issue by x3inspire** [OpenSTDL/CrunchyDL#40]
Hi, i tried to download [https://www.crunchyroll.com/series/G0XHWM130/vampire-dormitory](url) and getting these error:

![image](https://github.com/OpenSTDL/CrunchyDL/assets/4635825/b83a1172-03d3-44ee-8658-491b6e00c045)

**Comment by x3inspire** [comment]
Update, using single episode link got an error episode not found.

[https://www.crunchyroll.com/watch/GG1U2JW2N/love-2-the-pretty-boy-is-targeted](url)
![image](https://github.com/OpenSTDL/CrunchyDL/assets/4635825/9f0e8785-1d77-4e54-9fbf-e5e367b339b6)

**Comment by x3inspire** [comment]
Updated...

I tried download 3 episode, in apps show completed but the output only show episode 01.

![image](https://github.com/OpenSTDL/CrunchyDL/assets/4635825/f6638b8b-b81d-4241-a964-28e6c6989686)

**Comment by x3inspire** [comment]
> Updated...
> 
> I tried download 3 episode, in apps show completed but the output only show episode 01.
> 
> ![image](https://private-user-images.githubusercontent.com/4635825/342567656-f6638b8b-b81d-4241-a964-28e6c6989686.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODczMDgsIm5iZiI6MTcxOTI4NzAwOCwicGF0aCI6Ii80NjM1ODI1LzM0MjU2NzY1Ni1mNjYzOGI4Yi1iODFkLTQyNDEtYTk2NC0yOGU2YzY5ODk2ODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMDM0MzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTU4ZWMzNWZmZTZlMWJiM2Q1OTUyOTU2MzZmMWEzNDE0ZTgzNWM4YTk3Yzg1YjA2NmY4ODk3ZTY0NGJlMzc0MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yP6SZUVSjMkNQ4m-d8cV1vmyNsVLZeKJCRJBM5DS45Y)

Ok nvm, this is because my naming setting issue.

**Comment by stratuma** [comment]
> Update, using single episode link got an error episode not found.
> 
> [https://www.crunchyroll.com/watch/GG1U2JW2N/love-2-the-pretty-boy-is-targeted](url) ![image](https://private-user-images.githubusercontent.com/4635825/342565128-9f0e8785-1d77-4e54-9fbf-e5e367b339b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTMyMTgsIm5iZiI6MTcxOTMxMjkxOCwicGF0aCI6Ii80NjM1ODI1LzM0MjU2NTEyOC05ZjBlODc4NS0xZDc3LTRlNTQtOWZiZi1lNWUzNjdiMzM5YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMTA1NTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg1NzhjOWNlOTI3ODdmYjg5NTA2NjE4Nzc3ZGQzZDZlY2JmNWQ3OTNlNjdkMzE0ZWZhZmFiMzY2YWNmOTg1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CuJr4clr8w3iJM14MFegOfF3DcWTRZa6wAIbnmMvRYU)

Yeah this bug is fixed, but not yet in a version.

**Comment by stratuma** [comment]
> Hi, i tried to download [https://www.crunchyroll.com/series/G0XHWM130/vampire-dormitory](url) and getting these error:
> 
> ![image](https://private-user-images.githubusercontent.com/4635825/342564374-b83a1172-03d3-44ee-8658-491b6e00c045.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTMyODcsIm5iZiI6MTcxOTMxMjk4NywicGF0aCI6Ii80NjM1ODI1LzM0MjU2NDM3NC1iODNhMTE3Mi0wM2QzLTQ0ZWUtODY1OC00OTFiNmUwMGMwNDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMTA1NjI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmVkNDQ0YjUwZDk1Y2Q3YjI1OGQ0NmMxZTgwMGFjYzhlMzU2NDhiYjI2MTA3NTJiYjdlNjRlYTZlMmNmNjQ1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rFmHZcgzxsl-Xb1pWy4En9w0tjmN3VEv6peYagkQnDo)

There could be alot of reasons why this error showes up

**Comment by stratuma** [comment]
Not a bug
