### ISSUE TITLE
[FEATURE] Add English Closed Captions on supported streams

### ISSUE THREAD

**Issue by KingGainer999** [OpenSTDL/CrunchyDL#41]
I often download videos with multiple audio tracks and sometimes CR includes a full closed caption track on a secondary English entry marked as "English [CC]" on their player. I can't see a way to get these to download with the currently available options, and selecting English subs only downloads the main English subs used for Japanese audio.

Is it possible to add either an additional language selection for the closed captions or set the English subtitles option to grab both versions of the subs?

**Comment by stratuma** [comment]
Hello,
I will investigate it and add it in the new version.

**Comment by stratuma** [comment]
can you please send me an anime where english caption is available?

**Comment by KingGainer999** [comment]
Sure, Gundam: The Witch from Mercury is one that has CCs. I can probably find a few more if needed.

https://www.crunchyroll.com/series/G79H2307W/mobile-suit-gundam-the-witch-from-mercury

**Comment by stratuma** [comment]
![grafik](https://github.com/OpenSTDL/CrunchyDL/assets/166541445/d226c55a-6531-434a-b2d8-9c45ce4054fb)

I can't find any english cc sub playlists

**Comment by Jaykoerner** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/166541445/343134137-d226c55a-6531-434a-b2d8-9c45ce4054fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MDM1MTcsIm5iZiI6MTcxOTQwMzIxNywicGF0aCI6Ii8xNjY1NDE0NDUvMzQzMTM0MTM3LWQyMjZjNTVhLTY1MzEtNDM0YS1iMmQ4LTljNDVjZTQwNTRmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQxMjAwMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTI0MTE2N2ZiMmVhMjU0NmM5YWY3YmIyNmYxOTllM2RiYzZhOGIwYTU2ZmFiNmY1ODU3ZWI3NDhiYTk4ZjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rDjltjQvbPJgbYKcFVP_3nUs4gpysPDq4J4PWNlV6AU)
> 
> I can't find any english cc sub playlists

I just check myself out of curiosity, but a English audio stream(at least for a US English language account) of that show does show a different CC for the English and Japanese audio/video streams,

Specifically (this is on the app), if I select English audio, my only option is English closed captions, with no other languages available and those closed captions are specific to following the words stated in the English version

**Comment by stratuma** [comment]
> I just check myself out of curiosity, but a English audio stream(at least for a US English language account) of that show does show a different CC for the English and Japanese audio/video streams,
> 
> Specifically (this is on the app), if I select English audio, my only option is English closed captions, with no other languages available and those closed captions are specific to following the words stated in the English version

I see, I found the cc in the eng dub version. I will see what I can do.

**Comment by stratuma** [comment]
Moving all feature requests to #14
