### ISSUE TITLE
[QUESTIONS / FEATURE] Couple of questions

### ISSUE THREAD

**Issue by Meivyn** [OpenSTDL/CrunchyDL#45]
Do you think an automated process of decrypting the stream would be seen as illegal if it uses an external service? I still really don't see the problem with all of that based on the fact that an account is *required* to download anyway. I've set up that service on my local version rather than dumping keys, personally, as it's just more convenient. 

Why are you using mp4decrypt/shaka to decrypt the streams rather than using ffmpeg built-in decryption module?

While I'm there, forcing the endpoint to be 1/stating that there is an unencrypted endpoint fallback should probably be removed from the code base considering that there's none left.

**Comment by stratuma** [comment]
> Do you think an automated process of decrypting the stream would be seen as illegal if it uses an external service? I still really don't see the problem with all of that based on the fact that an account is _required_ to download anyway. I've set up that service on my local version rather than dumping keys, personally, as it's just more convenient.

It depends on your current location, I could implement automated decryption using a external source since its legal in my place.

> Why are you using mp4decrypt/shaka to decrypt the streams rather than using ffmpeg built-in decryption module?

Because shaka is better and faster than ffmpeg, I often got broken videos because it failed to decrypt right.

> While I'm there, forcing the endpoint to be 1/stating that there is an unencrypted endpoint fallback should probably be removed from the code base considering that there's none left.

Since v1.2.3 the switch endpoint has (DRM PROTECTED) in its name like any other endpoint.

**Comment by Meivyn** [comment]
> It depends on your current location, I could implement automated decryption using a external source since its legal in my place.

Well, probably not legal in here, and my stuff is kinda messy as it relies on plain requests/manual parsing, but it works without having to dump a key. I can fork and push changes if you want to take a look. But probably not clean enough to PR in there.

> Since v1.2.3 the switch endpoint has (DRM PROTECTED) in its name like any other endpoint.

What I mean is this and similar parts in the same file:

https://github.com/OpenSTDL/CrunchyDL/blob/ff4622b14aa68fec8c37e24123c2fa9cbc4d4fa4/src/api/routes/crunchyroll/crunchyroll.service.ts#L17-L22

And this:

https://github.com/OpenSTDL/CrunchyDL/blob/ff4622b14aa68fec8c37e24123c2fa9cbc4d4fa4/components/Settings/Crunchyroll.vue#L34

Those doesn't make sense anymore considering that there's no non-DRM stream left. It would just override user's selected endpoint.

**Comment by stratuma** [comment]
> > It depends on your current location, I could implement automated decryption using a external source since its legal in my place.
> 
> Well, probably not legal in here, and my stuff is kinda messy as it relies on plain requests/manual parsing, but it works without having to dump a key. I can fork and push changes if you want to take a look. But probably not clean enough to PR in there.

Idk, if I implement it I will make my own service, since I cannot trust external sources to handle sensible data.

> > Since v1.2.3 the switch endpoint has (DRM PROTECTED) in its name like any other endpoint.
> 
> What I mean is this and similar parts in the same file:
> 
> https://github.com/OpenSTDL/CrunchyDL/blob/ff4622b14aa68fec8c37e24123c2fa9cbc4d4fa4/src/api/routes/crunchyroll/crunchyroll.service.ts#L17-L22
> 
> And this:
> 
> https://github.com/OpenSTDL/CrunchyDL/blob/ff4622b14aa68fec8c37e24123c2fa9cbc4d4fa4/components/Settings/Crunchyroll.vue#L34
> 
> Those don't make sense anymore considering that there's no non-DRM stream left. It would just override the user's selected endpoint.

Oh yeah, thx for reminding me, I will remove them.

**Comment by Meivyn** [comment]
If you want to implement it yourself, could probably use the source code. I think it uses [https://github.com/devine-dl/pywidevine](https://github.com/devine-dl/pywidevine/blob/master/pywidevine/serve.py) but I am not entirely sure. As far as I know though, there's no sensitive data that is sent to the external API. All it does is decrypting based on the PSSH and stuff returned by the official Widevine endpoint.

**Comment by stratuma** [comment]
> If you want to implement it yourself, could probably use the source code. I think it uses [https://github.com/devine-dl/pywidevine](https://github.com/devine-dl/pywidevine/blob/master/pywidevine/serve.py) but I am not entirely sure. As far as I know though, there's no sensitive data that is sent to the external API. All it does is decrypting based on the PSSH and stuff returned by the official Widevine endpoint.

Pywidevine does not more than my project atm, you still need the device keys.
I could host a server in russia that accepts license requests, but instead of sending the data to request cenc, it sends back the clearkeys.
Another way is to send custom mpd's that contain the clearkeys directly.

**Comment by Meivyn** [comment]
Well, the service I am talking about might be using device keys internally, but user definitely don't have to provide one.

**Comment by stratuma** [comment]
> Well, the service I am talking about might be using device keys internally, but user definitely don't have to provide one:
> 
>     * Open a session
> 
>     * Get the challenge data by sending the PSSH
> 
>     * Send challenge data to the official Widevine license endpoint
> 
>     * Send the returned license data to the API which will parse it
> 
>     * Get decryption keys
> 
>     * Close the session
> 
> 
> It's a matter of 6 requests. It definitely use pywidevine which might require keys, but it's more convenient for the user.

If they use device keys internally I could setup such a service too, and I'm safe on my part.

The steps you listed are necessary, even with the service you suggest, because you need the challange data anyway.

**Comment by Meivyn** [comment]
I think some would appreciate it if you could setup such a service or use an existing one. Dumping keys is not exactly user-friendly.

While I'm asking questions though, why there are hardcoded tokens in `crunchyroll.service.ts`?

Also, could you clarify what the audio quality is for? Especially the one with `(2)` (I didn't look at the code myself, just find it weird).

**Comment by stratuma** [comment]
> I think some would appreciate it if you could setup such a service or use an existing one. Dumping keys is not exactly user-friendly.

I will do it when I have time.

> While I'm asking questions though, why there are hardcoded tokens in `crunchyroll.service.ts`?

These are the default token to do the login request, that token is hardcoded even in the crunchyroll apk's.

> Also, could you clarify what the audio quality is for? Especially the one with `(2)` (I didn't look at the code myself, just find it weird).

Crunchyroll somehow provides two 44.10 kHz playlists. There is no quality or any other difference between the playlists.
![grafik](https://github.com/OpenSTDL/CrunchyDL/assets/166541445/ff6135b6-1c1c-44be-8fd2-0deb61456bac)

**Comment by stratuma** [comment]
Moving all feature requests to #14
