### ISSUE TITLE
[BUG] Login Error 401

### ISSUE THREAD

**Issue by Raphael1512** [OpenSTDL/CrunchyDL#48]
Hi, I got this error again, I logged out and tried to log in again but nothing.

![Screenshot 2024-07-02 184500](https://github.com/OpenSTDL/CrunchyDL/assets/166643560/a7c445e8-cca8-4118-9d41-005a4ec1d50e)

**Comment by stratuma** [comment]
The error says invalid credentials, so you probably changed the password or something

**Comment by Tobolobo** [comment]
Same here, Login in the browser works, but not in the downloader.

**Comment by Tobolobo** [comment]
That was a quick reply. :) I'll try every now and then.

**Comment by stratuma** [comment]
I tried it myselfe, I can't replicate it somehow.

**Comment by Tobolobo** [comment]
Browser-based Endpoints seem not to work properly. The Switch Endpoint works fine.

**Comment by Raphael1512** [comment]
Thank you!

**Comment by stratuma** [comment]
Crunchyroll changed the login auth proccess again. Idiots

**Comment by stratuma** [comment]
Fixed in v1.2.4
