### ISSUE TITLE
[BUG] 1080p will not download if video is below 1080p (1072p)

### ISSUE THREAD

**Issue by Fu2chN** [OpenSTDL/CrunchyDL#51]
**Describe the bug**
Don't download a 1080p (1920/1072) automatic switch to 720p.

**To Reproduce**
Saki - Season 01 are in this resolution.
https://www.crunchyroll.com/fr/watch/G65VPX0E6/encounter

**Expected behavior**
Download this resolution.

**Comment by stratuma** [comment]
Thx for the bugreport, I will write a fix for that when I have time.
