### ISSUE TITLE
[BUG] Wrong episode name and number when episode is a special

### ISSUE THREAD

**Issue by Fu2chN** [OpenSTDL/CrunchyDL#53]
**Describe the bug**
The special episodes of Shadowverse are poorly downloaded, possibly due to the same file name. 
They are the same video.

**To Reproduce**
Shadowverse specials episode Season 01 (3 titles) Season 02 (4 titles)
https://www.crunchyroll.com/fr/series/GYEX244X6/shadowverse

![image](https://github.com/OpenSTDL/CrunchyDL/assets/13276983/59e3eda9-9886-4cac-b79c-f15aa1ff4573)

**Expected behavior**
Correctly download this.

**Comment by stratuma** [comment]
thx for the bugreport, I will investigate it.
