### ISSUE TITLE
[BUG] Hardsub Playlist not found

### ISSUE THREAD

**Issue by AsIFall** [OpenSTDL/CrunchyDL#54]
**Describe the bug**
Before starting the download you will now need to chose hardsub file. When hardsub file is chosen and the download starts an error window opens shortly after starting the download. The error says that the Hardsub Playlist could not be found and only the Japanese playlist will be downloaded. This leads that the downloaded video does not have any subtitles. If I do not chose any hardsubs, the error message does not appear but the video has no subtitles.

![Screenshot (238)](https://github.com/OpenSTDL/CrunchyDL/assets/110290203/6c3ea58b-9c65-4917-8bd3-07d9e05141ff)
![Screenshot (239)](https://github.com/OpenSTDL/CrunchyDL/assets/110290203/2ff23f6b-2f9e-4465-a442-940e51bf9a56)

**Comment by stratuma** [comment]
Like I explained in #46 :

If the error hardsub playlist not found appears it means that crunchyroll didn't have a hardsub playlist atm (that happens often with simulcast episodes)

**Comment by acteiaa** [comment]
Answering your previous question, the caption really exists; I downloaded it using hama3254's old Crunchyroll-Downloader-v3.0. Before this update, subtitles were normally downloaded for my language, PT-BR, which I would like to see added as an option, as it currently only has PT. Previously, Hardsub downloaded forced subtitles when the content was dubbed, and downloaded normally when it wasn't.

**Comment by AsIFall** [comment]
I downgraded to version 1.2.3. The download seems to be working without any issue. The subtitles are now availble.

**Comment by stratuma** [comment]
This looks like the same error with #60 , crunchyroll sometimes don't include the hardsubs in the playlist like they don't include the dubs sometimes

**Comment by stratuma** [comment]
Fixed in v1.2.5
