### ISSUE TITLE
I don't know if it's a bug, regarding the use of a proxy.

### ISSUE THREAD

**Issue by Vorffeed** [OpenSTDL/CrunchyDL#59]
How do I use the proxies?, because it doesn't give me the option to select anything and there are the three that appear offline.

![image](https://github.com/OpenSTDL/CrunchyDL/assets/10000442/cd80d0f9-1ed4-4914-a274-c964758f9ae6)

I am using the latest version

**Comment by stratuma** [comment]
The proxies are getting ddosed everytime.
