### ISSUE TITLE
bug failed gets versions

### ISSUE THREAD

**Issue by Gremory17** [OpenSTDL/CrunchyDL#63]
Describe the bug
When trying to download any file the error failed gets versions appears v1.2.5

To Reproduce
add link
add to download 
error failed gets versions

![image](https://github.com/OpenSTDL/CrunchyDL/assets/163672617/d6107432-91ee-4545-80b2-0c20f810f20a)
![image](https://github.com/OpenSTDL/CrunchyDL/assets/163672617/01c97adf-52c8-4b6b-b0fe-d7ba8acc10e5)

**Comment by TaciturnShadow** [comment]
1.2.4 works fine.

**Comment by Gremory17** [comment]
> 1.2.4 works fine.

I want to downgrade to version 1.2.4 but I can't find the file to do it

**Comment by stratuma** [comment]
I'm coding a fix rn, give me a minute

**Comment by stratuma** [comment]
Fixed in v1.2.6

**Comment by Gremory17** [comment]
> Fixed in v1.2.6

thanks :D

**Comment by acteiaa** [comment]
![image](https://github.com/user-attachments/assets/1ac4ad29-9c70-441f-a5b1-eea033081e25)
unfortunately another error

**Comment by acteiaa** [comment]
It just downloads the video with subtitles in text format, which is not useful as it is not in ASS format.

**Comment by Haldrie** [comment]
> It just downloads the video with subtitles in text format, which is not useful as it is not in ASS format.

This should be posted as a new issue since it is unrelated to this one but ever since the merge with Funimation content a lot of shows are coming with VTT format subs which is what Funimation had which are similar to SRT and there is a converter for that. I've never used hard subs with this software so not sure what is going on with that but I wonder if maybe that has something to do with it.

**Comment by acteiaa** [comment]
> > It just downloads the video with subtitles in text format, which is not useful as it is not in ASS format.
> 
> This should be posted as a new issue since it is unrelated to this one but ever since the merge with Funimation content a lot of shows are coming with VTT format subs which is what Funimation had which are similar to SRT and there is a converter for that. I've never used hard subs with this software so not sure what is going on with that but I wonder if maybe that has something to do with it.

Maybe that was it. The Hama program always downloads in its default format, which is ASS, and it is the only thing that is working and has never stopped so far. That's why I asked myself why you use VTT instead of ASS, since the ASS format is not protected and there has never been an error.
