### ISSUE TITLE
[BUG] ADN german dub not showing up

### ISSUE THREAD

**Issue by Aiyomi-Irirako** [OpenSTDL/CrunchyDL#8]
**Describe the bug**
Deutsche Sprache kann nicht im Downloader ausgewählt. Es wird nur Japanisch als Sprachauswahl angegeben.

**To Reproduce**
1. Man gehe auf add Download
2. Wählt ADN aus
3. Such nach einer Serie mit deutscher Sprache z.B. AESTHETICA OF A ROGUE HERO
4. Wählt den Anime aus
5. Klickt auf Next
6. Bei Dubs wird nur Japanisch angezeigt, obwohl Deutsch und Japanisch verfügbar ist

**Expected behavior**
Dass man Deutsch auswählen

**Screenshots**
Downloader:
https://i.imgur.com/psxwgon.png

ADN Website:
https://i.imgur.com/doL5C4O.png

**Additional context**
Ich hoffe deutsch ist in Ordnung, da ADN neben Frankreich nur in Deutschland ist.

Danke für den tollen Downloader und für die Arbeit die du bzw. ihr da reinsteckt.

**Comment by stratuma** [comment]
Danke für den Bugreport.
Ich werde mir das die nächsten Tage anschauen und fixen

**Comment by Aiyomi-Irirako** [comment]
Vielen Dank.
Und auch Danke, dass du so einen tollen Downloader gemacht hast.

**Comment by Aiyomi-Irirako** [comment]
Hi,

ich wollte mal vorsichtig nachfragen, wie der Stand der Dinge ist.

Tut mir leid, falls ich dich nerven sollte

LG

**Comment by stratuma** [comment]
Ich muss mir nochmal ein ADN account zulegen um es testen und fixen zu können, außerdem hab ich momentan leider wenig Zeit.

**Comment by Aiyomi-Irirako** [comment]
Falls du die 7 € haben möchtest, kann ich dir die gerne schicken :D

**Comment by stratuma** [comment]
Fixed in v1.2.4
