### ISSUE TITLE
[DRM] Non-DRM Endpoints investigation

### ISSUE THREAD

**Issue by stratuma** [OpenSTDL/CrunchyDL#9]
Since yesterday the switch api has drm.
I'm trying to find a new non-drm endpoint.
Otherwise this tool will only work with l3 keys.

**Comment by stratuma** [comment]
For everyone wanting to download now here is a guide to obtain L3 keys:
https://simpcity.su/threads/guide-for-getting-drm-content-wip.181199/

Just put the keys you get here:
![grafik](https://github.com/stratuma/Crunchyroll-Downloader-v4.0/assets/166541445/15753ac9-2194-46dd-a03e-6e8e4bc20e6f)

**Comment by stratuma** [comment]
After checking the switch endpoint it looks like there is OMA drm, so no bypass.

**Comment by stratuma** [comment]
Maybe I found something.
I'm still investigating it.

**Comment by x3inspire** [comment]
> For everyone wanting to download now here is a guide to obtain L3 keys: https://simpcity.su/threads/guide-for-getting-drm-content-wip.181199/
> 
> Just put the keys you get here: ![grafik](https://private-user-images.githubusercontent.com/166541445/341045794-15753ac9-2194-46dd-a03e-6e8e4bc20e6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyODU1NDAsIm5iZiI6MTcxOTI4NTI0MCwicGF0aCI6Ii8xNjY1NDE0NDUvMzQxMDQ1Nzk0LTE1NzUzYWM5LTIxOTQtNDZkZC1hMDNlLTZlOGU0YmMyMGU2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNVQwMzE0MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjA0NDdiZjI4ZWQyZTMyYjY3MjhmMzI3MDA3M2UzOGRjNDRkZDY1N2FmMTYwNGIzNWNiN2ZkMGRjNGJmZDk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yE8CEpsr37cGb8KfzHdYWrzwg_mPXmCYnrP-VRv7YWQ)

So we just use DRM key from Bitmovin, or must be from Crunchyroll player?

**Comment by stratuma** [comment]
> So we just use DRM key from Bitmovin, or must be from Crunchyroll player?

You can use any key, as long it is a L3 Widevine key.
